# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bqxu's Tech
email: bcaring@163.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://bqxu.me" # the base hostname & protocol for your site
github_username:  bqxu

# Build settings
markdown: kramdown
kramdown:
   input:  GFM
   hard_wrap: false
   math_engine: mathjax

lsi: false
safe: true
incremental: false
highlighter: rouge

gist:
   noscript: false

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title.html
    output: true
  article:
    permalink: /article/:year/:month/:day/:title.html
    output: true


# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false



# Outputting
paginate: 10
paginate_path: "blog/page:num"
timezone:      null


#  javascript:
#    name: javascript
#    output: true
#  style:
#    name: stylesheet
#    output: true
#  node:
#    name: nodejs
#    output: true
#  soft:
#    name: soft
#    output: true
#  css3:
#    name: css3
#    output: true
#  java:
#      output: true
#  framework:
#    output: true


gems:
  - jekyll-coffeescript
  - jekyll-paginate

